### ISSUE TITLE
Add redirect_from: tag to many pages

### ISSUE THREAD

**Issue by boturnbow** [safmt/www.masfaaonline.org#2]
Use google search results for old site to create redirects to new pages: https://encrypted.google.com/search?hl=en&q=masfaaonline.org

It usually takes a long time for google to re-index infrequently updated sites so these links will stay out there for a long time.

**Comment by joaquinvaldez** [comment]
Do you mean adding "redirect_from: oldsite/page.html" in the preamble of the new pages? 

https://github.com/jekyll/jekyll-redirect-from

Thanks.

**Comment by boturnbow** [comment]
Yep, that gem works on github pages. In the front matter for /documents/
index.md for example you would add:

redirect_from: /document-list.jsp

Some pages might have multiples. There is a different syntax for that.

**Comment by joaquinvaldez** [comment]
Addressed by this commit: https://github.com/safmt/www.masfaaonline.org/commit/86cb5cf4f2822c21688fc428eaa8e3028c000466
